[tools]
node = "24"
podman = "latest"

[tasks]
# See package.json for direct npm tasks.
build = "podman build -f Dockerfile . -t twotech"
run-dev = "podman run -p 80:8080 --rm twotech"

[env]
ONETECH_MOD_NAME = "Two Hours One Life"
ONETECH_MOD_URL = "https://twohoursonelife.com/"
ONETECH_PROCESS_GIT_URL = "https://github.com/twohoursonelife/OneLifeData7"
